app_id: "3962bc1f-9d4f-4f6f-b8d1-bec4d2371748" 
app_secret: "abr7Q~kXDSzF~T8IgHIB~4m6nbMMARvUYG5ey" 
redirect: "http://localhost:8000/callback"
scopes:
    - user.read   
    - mailboxsettings.read   
    - calendars.readwrite authority: "https://login.microsoftonline.com/3962bc1f-9d4f-4f6f-b8d1-bec4d2371748"
